
eureka:
  client:
    registerWithEureka: true # 이 서버를 eureka에 등록할 지 여부
    fetchRegistry: true # registry에 있는 정보를 가져올 지 여부
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/ # eureka 서버 정보

attic:
  version: 1.0